/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.DAO;
import controleur.DAO_Factory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.Enseignement;
import modele.Inscription;
import modele.Personne;

/**
 * Permet l'ajout d'un utilisateur a la base de donnees
 * @author Marine
 */
public class CreationCompte extends javax.swing.JFrame {

    /**
     * Crees une nouvelle JForm CreationCompte
     */
    public CreationCompte() {
        initComponents();
        jLabelDiscipline.setVisible(false);
        jComboBoxDiscipline.setVisible(false);
        populateComboBoxes();
    }

    /**
     * Connecte le programme a la base de donnees
     */
    protected static Connection connect = null;
        static {
            Connection tmp = null;

            try {
                Class.forName("com.mysql.jdbc.Driver");
                tmp = DriverManager.getConnection("jdbc:mysql://localhost/gestionEcole", "root", "");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DAO_Factory.class.getName()).log(Level.SEVERE, null, ex);
            }
            connect = tmp;
        }

    /**
     *
     */
    public void populateComboBoxes(){
            try {
                ResultSet result = this.connect.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY).executeQuery(
                "SELECT id, nom, id_AnneeScolaire FROM Classe"
                );
                while(result.next()) {
                    jComboBoxClasse.addItem(result.getString("id") + "_" +
                    result.getString("nom") + "_" +
                    result.getString("id_AnneeScolaire"));
                }
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } try {
                ResultSet result = this.connect.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY).executeQuery(
                "SELECT id, nom FROM Discipline"
                );
                while(result.next()) {
                    jComboBoxDiscipline.addItem(result.getString("id") + "_" + result.getString("nom"));
                }
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jCheckBoxEnseignant = new javax.swing.JCheckBox();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonRetour = new javax.swing.JButton();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelEnseignantCheck = new javax.swing.JLabel();
        jLabelDiscipline = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jComboBoxClasse = new javax.swing.JComboBox<>();
        jLabelClasse = new javax.swing.JLabel();
        jComboBoxDiscipline = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setBackground(new java.awt.Color(239, 239, 237));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 239, 237));
        jLabel1.setText("Creation d'un compte");

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        jTextFieldLogin.setBackground(new java.awt.Color(228, 233, 237));

        jTextFieldPrenom.setBackground(new java.awt.Color(228, 233, 237));

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jCheckBoxEnseignant.setForeground(new java.awt.Color(52, 73, 94));
        jCheckBoxEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEnseignantActionPerformed(evt);
            }
        });

        jTextFieldPassword.setBackground(new java.awt.Color(228, 233, 237));

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabelNom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNom.setText("Nom :");

        jLabelPrenom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrenom.setText("Prenom :");

        jLabelEnseignantCheck.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnseignantCheck.setText("Enseignant :");

        jLabelDiscipline.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiscipline.setText("Discipline :");

        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Login :");

        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password :");

        jLabelClasse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasse.setText("Classe :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNom)
                            .addComponent(jLabelPrenom)
                            .addComponent(jLabelEnseignantCheck)
                            .addComponent(jLabelDiscipline)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelClasse))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jCheckBoxEnseignant)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jTextFieldNom)
                            .addComponent(jComboBoxClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDiscipline, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClasse))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiscipline)
                    .addComponent(jComboBoxDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEnseignantCheck)
                    .addComponent(jCheckBoxEnseignant))
                .addGap(18, 18, 18)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetour)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(422, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        if (jTextFieldLogin.getText().isEmpty() ||
                jTextFieldPrenom.getText().isEmpty() ||
                jTextFieldPassword.getText().isEmpty() ||
                jComboBoxClasse.getSelectedIndex() == -1 ||
                (jComboBoxDiscipline.getSelectedIndex() == -1 &&
                jCheckBoxEnseignant.isSelected()))
            JOptionPane.showMessageDialog(null, "Merci de remplir tous les champs");
            else {
                int type = 0;
                if (jCheckBoxEnseignant.isSelected())
                    type = 1;
                DAO<Personne> daoP = DAO_Factory.getPersonneDAO();

                Personne newUser = new Personne(0, jTextFieldNom.getText(),
                                                   jTextFieldPrenom.getText(),
                                                   jTextFieldLogin.getText(),
                                                   jTextFieldPassword.getText(),
                                                   type);
                if(!daoP.create(newUser)) {
                    JOptionPane.showMessageDialog(null, "Une erreur est survenue");
                    this.setVisible(false);
                    new CreationCompte().setVisible(true);
                }

                int newUserId = 0;
                try {
                    ResultSet result = this.connect.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY).executeQuery(
                    "SELECT MAX(id) FROM Personne"
                    );
                    if (result.first())
                    newUserId = result.getInt("MAX(id)");
                } catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                String parts[] = jComboBoxClasse.getSelectedItem().toString().split("_");
                int idClasse = Integer.parseInt(parts[0]);
                if(type != 1) {
                    DAO<Inscription> daoI = DAO_Factory.getInscriptionDAO();
                    Inscription newI = new Inscription(0, idClasse, newUserId);
                    if(!daoI.create(newI)) {
                        JOptionPane.showMessageDialog(null, "Une erreur est survenue");
                        this.setVisible(false);
                        new CreationCompte().setVisible(true);
                    }
                } else {
                    String partsDisc[] = jComboBoxDiscipline.getSelectedItem().toString().split("_");
                    int idDisc = Integer.parseInt(partsDisc[0]);
                    DAO<Enseignement> daoE = DAO_Factory.getEnseignementDAO();
                    Enseignement newE = new Enseignement(0, idClasse, idDisc, newUserId);
                    if(!daoE.create(newE)) {
                        JOptionPane.showMessageDialog(null, "Une erreur est survenue");
                        this.setVisible(false);
                        new CreationCompte().setVisible(true);
                    }
                }
                this.setVisible(false);
                new ConnexionGraphique().setVisible(true);
            }
        }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.setVisible(false);
        new ConnexionGraphique().setVisible(true);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jCheckBoxEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEnseignantActionPerformed
        if (jCheckBoxEnseignant.isSelected()) {
            jComboBoxDiscipline.setVisible(true);
            jLabelDiscipline.setVisible(true);
        } else {
            jComboBoxDiscipline.setVisible(false);
            jLabelDiscipline.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxEnseignantActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JCheckBox jCheckBoxEnseignant;
    private javax.swing.JComboBox<String> jComboBoxClasse;
    private javax.swing.JComboBox<String> jComboBoxDiscipline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelDiscipline;
    private javax.swing.JLabel jLabelEnseignantCheck;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
