/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import controleur.DAO_Factory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modele.Personne;
import modele.Bulletin;
/**
 * Interface permettant de selectionner l'eleve dont on veut modifier le Bulletin, DetailBulletin ou Evaluation.
 * Permet aussi la selection du bulletin que nous allons modifier.
 * @author Marine
 */
public class GestionSelectionEleveGraphique extends javax.swing.JFrame {

       private Personne user;
       private Bulletin bulletin;
       private int id_eleve;


    /**
     * Crees une nouvelle JForm GestionSelectionEleveGraphique
     * @param user Personne connectee Personne connecteeUtilisateur necessaire a la creation de la forme
     */
    public GestionSelectionEleveGraphique(Personne user) {
        initComponents();
        tableEleve.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            if (tableEleve.getSelectedRow() != -1)
                getIdEleve();
                updateComboBox();
        }
    });
        this.user = user;
    }

    /**
     * Connecte le programme a la base de donnees
     */
    protected static Connection connect = null;
        static {
            Connection tmp = null;

            try {
                Class.forName("com.mysql.jdbc.Driver");
                tmp = DriverManager.getConnection("jdbc:mysql://localhost/gestionEcole", "root", "");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DAO_Factory.class.getName()).log(Level.SEVERE, null, ex);
            }
            connect = tmp;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSelect = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEleve = new javax.swing.JTable();
        retourButton = new javax.swing.JButton();
        SelectButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBulletin = new javax.swing.JComboBox();
        searchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 90, 253));

        jLabelSelect.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSelect.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelSelect.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelect.setText("Sélection de l'élève");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelSelect)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelSelect)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        tableEleve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prénom", "Nom", "Niveau", "Classe"
            }
        ));
        jScrollPane2.setViewportView(tableEleve);

        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        SelectButton.setText("Séléctionner");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recherche par nom ou prénom:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retourButton)
                    .addComponent(SelectButton))
                .addGap(24, 24, 24))
        );

        jComboBoxBulletin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectionner Bulletin" }));
        jComboBoxBulletin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxBulletinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxBulletinMousePressed(evt);
            }
        });
        jComboBoxBulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBulletinActionPerformed(evt);
            }
        });

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBoxBulletin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(jComboBoxBulletin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        this.setVisible(false);
        new EnseignantGraphique(user).setVisible(true);
    }//GEN-LAST:event_retourButtonActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
        this.setVisible(false);
        new GestionChoixModifGraphique(user, id_eleve, bulletin).setVisible(true);
    }//GEN-LAST:event_SelectButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        displayTable();
    }//GEN-LAST:event_searchFieldKeyReleased

    private void jComboBoxBulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBulletinActionPerformed
              try {
            String parts[] = jComboBoxBulletin.getSelectedItem().toString().split("_");
            ResultSet result = RechercheGraphique.connect.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY).executeQuery(
                        "SELECT * FROM  Bulletin b, Inscription i WHERE i.id=b.id_Inscription AND b.id='" + parts[0] + "'"
                );

            if(result.first()){
                bulletin = new Bulletin(result.getInt("id"), result.getString("nom"),result.getString("appreciation"),result.getInt("id_Trimestre"),result.getInt("id_Inscription"));
            }
              } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jComboBoxBulletinActionPerformed

    private void jComboBoxBulletinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBulletinMouseClicked

    }//GEN-LAST:event_jComboBoxBulletinMouseClicked

    private void jComboBoxBulletinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBulletinMousePressed

    }//GEN-LAST:event_jComboBoxBulletinMousePressed

    private Object[] appendValue(Object[] obj, Object newObj) {
        ArrayList<Object> temp = new ArrayList<Object>(Arrays.asList(obj));
        temp.add(newObj);
        return temp.toArray();
    }

    /**
     *
     */
    public void displayTable(){
        DefaultTableModel tableModel = (DefaultTableModel) tableEleve.getModel();
        tableModel.setRowCount(0);

        try {
            String searchQuery = searchField.getText();
            ResultSet result = RechercheGraphique.connect.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY).executeQuery(
                        "SELECT * FROM Personne p, Inscription i, Classe c, Niveau n WHERE p.id=i.id_Personne AND i.id_Classe=c.id AND c.id_Niveau=n.id AND (p.nom LIKE '%" + searchQuery + "%' OR p.prenom LIKE '%" + searchQuery + "%')"
                );
           while(result.next()){

             Object[] rowToInsert = new Object[]{};

              String strToInsert = result.getString("i.id");
                    rowToInsert = appendValue(rowToInsert, strToInsert);
               strToInsert = result.getString("p.prenom")
                                        .replaceAll(searchQuery, "<b><font color=\"rgb(159,90,253)\">" + searchQuery + "</b></font>");
                    rowToInsert = appendValue(rowToInsert, "<html>" + strToInsert);

               strToInsert = result.getString("p.nom")
                                        .replaceAll(searchQuery, "<b><font color=\"rgb(159,90,253)\">" + searchQuery + "</b></font>");
                    rowToInsert = appendValue(rowToInsert, "<html>" + strToInsert);

               strToInsert = result.getString("n.nom");
                    rowToInsert = appendValue(rowToInsert, "<html>" + strToInsert);
               strToInsert = result.getString("c.nom");

                    rowToInsert = appendValue(rowToInsert, "<html>" + strToInsert);

                    tableModel.addRow(rowToInsert);

            }

        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Votre requête a échoué. Merci de réessayer");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     *
     */
    public void getIdEleve() {
            int column = 0;
            int row = tableEleve.getSelectedRow();
            String selected_row = tableEleve.getModel().getValueAt(row, column).toString();
            this.id_eleve = Integer.parseInt(selected_row);
    }

    /**
     *
     */
    public void updateComboBox()
    {
        //jComboBoxBulletin.removeAll();
        jComboBoxBulletin.setModel(new DefaultComboBoxModel());
        try {
                String searchQuery = searchField.getText();
                ResultSet result = RechercheGraphique.connect.createStatement(
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY).executeQuery(
                "SELECT * FROM Bulletin b, Trimestre t WHERE b.id_Inscription = " + this.id_eleve + " AND t.id=b.id_Trimestre"
                );
                while(result.next())
                    jComboBoxBulletin.addItem(result.getString("b.id") + "_" + result.getString("nom") + "_" + result.getString("t.numero"));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectButton;
    private javax.swing.JComboBox jComboBoxBulletin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton retourButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tableEleve;
    // End of variables declaration//GEN-END:variables
}
